- datetime:
    format:
      timeStyle: short
      dateStyle: long
    locale: en-US
    
- resources:
    cpu: true
    memory: true
    disk: /mnt/data # Using your mapped environment path

- search:
    provider: duckduckgo
    focus: true